# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = true
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.21"
  src = "src"
  test = "test"
  fs_permissions = [{ access = "read", path = "./broadcast" }, { access = "read", path = "./reports" }]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  mumbai = { key = "${API_KEY_MUMBAISCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 140
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  mumbai = "{RPC_ENDPOINT_MUMBAI}"
  polygon = "{RPC_ENDPOINT_POLYGON}"
